# Generated by Django 4.0.2 on 2022-02-06 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShipyardGiftProject', '0004_prize'),
    ]

    operations = [
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employers', to='ShipyardGiftProject.employer')),
                ('prize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='ShipyardGiftProject.prize')),
            ],
        ),
    ]
